{ config, lib, pkgs, modulesPath, ... }: {
  networking.hostName = "SargoLaptop";
  networking.defaultGateway = "192.168.1.201";

  # Do not modify this section, It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/74a2b8ac-3e60-4b09-800e-844698e161fe";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-bc0294ed-e2cf-442c-9341-86b0777f1c6c".device =
    "/dev/disk/by-uuid/bc0294ed-e2cf-442c-9341-86b0777f1c6c";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/6624-CE14";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/9241452f-368d-4e95-99cc-7ec8654c13a1"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

}
