{ config, lib, pkgs, modulesPath, ... }: {
  networking.defaultGateway = "192.168.1.200";
  networking.hostName = "SargoSummit"; # Define your hostname.

  # Do not modify this section, It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/84590d94-496c-4396-8e3c-5fcee229bd86";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-6532690c-cd10-43c4-be08-856ee3e02ebc".device =
    "/dev/disk/by-uuid/6532690c-cd10-43c4-be08-856ee3e02ebc";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/B5FB-AC7D";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/fb052a14-7a1e-44f6-8bb5-077d607c9362"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

}
